name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        phpunit: [7.*, 8.*, 9.*]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
            - phpunit: 8.*
              php: 7.1
            - phpunit: 9.*
              php: 7.1
            - phpunit: 9.*
              php: 7.2

    runs-on: ubuntu-latest
    name: "PHP: ${{ matrix.php }}; PHPUnit: ${{ matrix.phpunit }}; Dependecies: ${{ matrix.dependency-version }}"

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, filter, json, libxml, mbstring, pcre, Phar, Reflection, SimpleXML, SPL, tokenizer, xml, xmlwriter
        coverage: none

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
          path: ~/.composer/cache/files
          key: dependencies-phpunit-${{ matrix.phpunit }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-v1

    - name: Install dependencies
      run: |
          composer remove infection/infection --dev
          composer require "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

    - name: Check platform requirements
      run: composer check-platform-reqs

    - name: Run tests
      run: ./vendor/bin/phpunit --verbose
